import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased p-10`}
      >
        <nav>
          <ul className="flex gap-4">
            <li><Link href='/'>Home</Link></li>
            <li><Link prefetch={false} href='/about'>About</Link></li>
            <li><Link prefetch={false} href='/blog'>Blog</Link></li>
          </ul>
        </nav>
        <hr/>
        {children}
      </body>
    </html>
  );
}
